name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Check import sorting with isort
        run: isort --check-only src/ tests/ examples/

      - name: Check code formatting with Black
        run: black --check src/ tests/ examples/

      - name: Lint with flake8 and mypy
        run: |
          flake8 src/ tests/
          mypy src/

      - name: Test with pytest
        run: pytest
